PREFIX : <http://www.semanticweb.org/ontologies/2020/uliege#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?bad_student_name ?course_label
WHERE
{
    ?student :followsCourse ?course ;
    		 :name ?bad_student_name .
    ?course rdfs:label ?course_label .

    ?lecture a :Lecture ;
             :includedIn ?course .

    FILTER NOT EXISTS {
    	?lecture :attendedBy ?student .
    }
}
ORDER BY ASC(?student)
