PREFIX : <http://www.semanticweb.org/ontologies/2020/uliege#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?student_name
       ?professor_name
       ?ml_publication_label
WHERE
{
    ?student :followsCourse ?course .
    ?course :taughtBy ?professor .
    ?ml_publication :hasAsAuthor ?professor.
    ?ml_publication :aboutTopic <https://en.wikipedia.org/wiki/Machine_learning> .

    ?student :name ?student_name .
    ?professor :name ?professor_name .
    ?ml_publication rdfs:label ?ml_publication_label .
}
ORDER BY ASC(?student_name)
